log_reader_homepage:
    path:  /log
    defaults: { _controller: ParasysLogReaderBundle:Default:log }
log_reader_tail:
    path: /tail
    defaults: { _controller: ParasysLogReaderBundle:Default:tail }
